// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcirvhqweskcxnutpirs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaXJ2aHF3ZXNrY3hudXRwaXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODk0ODAsImV4cCI6MjA2MjU2NTQ4MH0.5ErSQx9sMA5Dn-Oc5Mlwi5_yT9gxpVtyuZ3QoIjee74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);